# 0、Julia软件安装

## 0-1、学习资源

- Julia主网站：[https://julialang.org/](https://julialang.org)
- Julia官方文档：[https://docs.julialang.org/en/v1/](https://docs.julialang.org/en/v1/)
- Julia扩展包查找：[https://juliahub.com/ui/Packages](https://juliahub.com/ui/Packages)
- 清华大学开源软件镜像网站：[https://mirror.tuna.tsinghua.edu.cn/help/julia/](https://help.mirrors.cernet.edu.cn/julia/)

## 0-2、Julia命令行程序的安装和使用

### 下载和解压`julia`软件包
```bash
wget https://julialang-s3.julialang.org/bin/linux/x64/1.7/julia-1.7.3-linux-x86_64.tar.gz
tar zxvf julia-1.7.3-linux-x86_64.tar.gz
```

### 添加环境变量
```bash
vim ~/.bashrc
export PATH="$PATH:/data/ustc/julia-1.7.3/bin"
source ~/.bashrc
```

### 将`Julia`添加到`Jupyter Notebook`
```julia
import Pkg
Pkg.add("IJulia")
```

# 1、概述

## 1-1、命令行运行`julia`启动交互式会话（REPL）

```bash
$ julia
  
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.3 (2022-05-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> 
```

## 1-2、`julia`基本命令

### 查看`julia`的配置情况：

In [1]:
versioninfo()

Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: Apple M2
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, westmere)


### 显示当前工作路径：

In [2]:
pwd()

"/Users/zhangzhengjie/Research/202406_Julia_tutorial"

### 更改工作目录：

In [3]:
cd("/Users/zhangzhengjie/Research/202406_Julia_tutorial/")

## 1-3、利用REPL执行源文件

### `julia`源程序用`.jl`作为扩展名，运行**当前目录下**的`my_program.jl`：

In [4]:
include("my_program.jl")


1*1=1 
2*1=2 2*2=4 
3*1=3 3*2=6 3*3=9 
4*1=4 4*2=8 4*3=12 4*4=16 
5*1=5 5*2=10 5*3=15 5*4=20 5*5=25 
6*1=6 6*2=12 6*3=18 6*4=24 6*5=30 6*6=36 
7*1=7 7*2=14 7*3=21 7*4=28 7*5=35 7*6=42 7*7=49 
8*1=8 8*2=16 8*3=24 8*4=32 8*5=40 8*6=48 8*7=56 8*8=64 
9*1=9 9*2=18 9*3=27 9*4=36 9*5=45 9*6=54 9*7=63 9*8=72 9*9=81 

## 1-4、REPL的提示模式

### REPL的5种提示模式：
- **Julia模式**：第一行开头为`julia>`的模式，为REPL的默认操作模式。
- **Help模式**：在Julia模式下键入`?`可进入Help模式查看帮助文档（按`Backspace`可退出Help模式）。如在`help?>`后输入：
```julia
print()
```
- **Shell模式**：在Julia模式下键入`;`可进入Shell模式（按`Backspace`可退出Shell模式）。如在`shell>`后输入：
```julia
cd /data/ustc/
```
- **i-search模式**：在Julia模式下同时按`Ctrl`键+`R`键可进入i-search模式（同时按`Ctrl`键+`C`键可退出i-search模式）。
- **pacakge模式**：在Julia模式下键入`]`可进入pacakge模式（按`Backspace`可退出pacakge模式），可通过运行如下命令来管理Package：
  - `help`：查看Package。
  - `status`：查看安装的Package列表。
  - `add xxx`：安装某个Package。
  - `build xxx`：使Package能够运行。
  - `update xxx`：更新Package到新版本。
  - `remove xxx`：删除Package。

## 1-5、REPL中的快捷键与注意事项

- 同时按`Ctrl`键+`D`键或输入`exit()`可退出REPL。
- 同时按`Ctrl`键+`C`键可中止当前正在运行的耗时较长的程序。
- 在REPL中，在代码的结尾加上`;`，则其结果不会被显示。
- 变量`ans`总会储存最新一行执行代码的结果。

# 2、数据类型与基本运算

## 2-1、常量与变量

### 常量的关键字是`const`

In [5]:
const e = 2.71828182845904523536

2.718281828459045

In [6]:
const pi = 3.14159265358979323846

3.141592653589793

### 变量类型

In [7]:
x = 10          # 整型变量

10

In [8]:
y = -10.0       # 浮点型变量

-10.0

In [9]:
z = 1 + 2im     # 复数变量

1 + 2im

In [10]:
k = 2//3        # 有理数变量

2//3

In [11]:
name = "zhang"  # 字符串变量

"zhang"

In [12]:
myc = 'A'       # 字符变量

'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)

## 2-2、整数与浮点数

### `julia`中的整数可直接写成`-123`。

In [13]:
# 64位系统：
typeof(-123)    # 用typeof()求某个值的类型

Int64

### `julia`中的浮点数可直接写成`0.123`，也可直接写成科学记数法形式`1.23e-1`。

In [14]:
typeof(1.23e-1)

Float64

### `julia`中的复数可直接写成`1+2im`。

In [15]:
typeof(1+2im)

Complex{Int64}

### `julia`中的字符用单引号`''`表示，字符串用双引号`“”`或三重双引号`""""""`表示。

In [16]:
typeof('A')

Char

In [17]:
typeof("ustc")

String

## 2-3、四则运算

| 表达式 | 说明 |  
| - | - |
| `-x` | 取相反数 |   
| `x + y` | 加法 |
| `x - y` | 减法 |
| `x * y` | 乘法 |
| `x / y` | 除法 |
| `x ÷ y` | 取`x / y`的整数部分 |
| `x \ y` | 反向除法，等价于`y / x` |
| `x ^ y` | `x`的`y`次幂 |
| `x % y` | 取余数，等价于`rem(x,y)` |

其中，`÷`的输入方法为键入`\div`后按`Tab`，如此还可输入`α`(\alpha)、`π`(\pi)、`∑`(\sum)、`≥`(\ge)、`≤`(\le)、`≠`(\ne)、`∈`(\in)等。

## 2-4、数学函数

- 常见等数学函数有：`log`，`exp`，`sqrt`，`sin`，`cos`，`tan`等。

- `divrem(x, y)`：同时返回`x`除以`y`的商和余数。

- `round(Int, x)`将`x`四舍五入到整数，`round(x, digits=2)`将`x`四舍五入到2位小数，`round(x)`将`x`四舍五入到0位小数的浮点数。

- `floor(Int, x)`求小于等于`x`的最大整数，`floor(x)`返回小于等于`x`的最大整数对应的浮点值。

- `ceil(Int, x)`求大于等于`x`的最大整数，`ceil(x)`返回大于等于`x`的最大整数对应的浮点值。

- `factorial(n)`计算阶乘。

## 2-5、字符串的其他操作

### `*`连接两个字符串：

In [18]:
"julia_" * "tutorial"

"julia_tutorial"

### `^`表示字符串重复：

In [19]:
"program" ^ 3

"programprogramprogram"

# 3、流程控制与逻辑运算

## 3-1、运算符

### **关系运算符**

| 等于 | 不等于 | 大于 | 小于 | 大于等于 | 小于等于 |
| - | - | - | - | - | - |
| `==` | `!=` | `>` | `<` | `>=` | `<=` |

### **逻辑运算符**

| 运算符 | 逻辑表达式 | 意义 |
| - | - | - |
| `&&` | `x && y` | 如果两个操作数都非零，则条件为真 |
| `\|\|` | `x \|\| y` | 如果两个操作数中有任意一个非零，则条件为真 |
| `!` | `! x` | 逆转操作数的逻辑状态 |

逻辑运算符优先级低于关系运算符；逻辑运算符内部优先级为`!` > `&&` > `||`。

## 3-2、if

### **一般格式**
```julia
if 条件1
    ......
elseif 条件2
    ......
else
    ......
end
```

### **嵌套if**
```julia
if 条件1
    ......
    if 条件2
        ......
    elseif 条件3
        ......
    else
        ......
    end
elseif 条件4
    ......
else
    ......
end
```

## 3-3、条件运算符及条件表达式

- 三元运算符`? :`，其构成的条件表达式为：
```julia
表达式1 ? 表达式2 : 表达式3
```

若`表达式1`的值为真，则返回`表达式2`的值，否则返回`表达式3`的值。

## 3-4、复合表达式

### **`begin`块**

In [20]:
t = begin
    x = 15
    y = 12
    z = 6
    x * y - z
end

174

### **链**

In [21]:
x = ( a = 2 ;
      b = 3 ;
      c = 6 ;
      a*b+c
)

12

## 3-5、异常处理

### **`try...catch`语句**

In [22]:
try
    sqrt(-2)
catch
    println("只有非负数才能求平方根！")
end

只有非负数才能求平方根！


### **`try...finally`语句**  

无论程序如何退出，`finally`语句总被执行。

In [23]:
try
    sqrt(-2)
catch
    println("只有非负数才能求平方根！")
finally
    println("我是finally语句！")
end

只有非负数才能求平方根！
我是finally语句！


# 4、循环

### **`while`循环**
```julia
while 表达式
    语句
end
```

在`julia`中没有`do...while`语句。

### **`for`循环**
```julia
for 迭代变量 in 可迭代对象
    语句
end
```

可迭代对象包含：字符串、序列、数组、迭代器等。

### **`for`循环中的`range()`函数**
```julia
range(start, stop[, step])
```

### **`break`和`continue`语句**
  - 使用`break`语句可以跳出`while`或`for`的本层循环。
  - 使用`continue`语句可以跳出当前迭代并继续到下一迭代。

# 5、函数与模块

## 5-1、内置函数

### **基本内置函数**
  | 函数 | 意义 |
  | - | - |
  | `println()` | 打印（结束自动换行） |
  | `readline()` | 读取一行 |
  | `readlines()` | 读取所有行成为一个数组 |

### **数学函数**
  | 数学函数 | 意义（返回值） |
  | - | - |
  | `round(x)` | 返回数字的四舍五入值，如`round(4.7)`返回5 |
  | `floor(x)` | 返回数字的下舍整数，如`floor(4.9)`返回4 |
  | `ceil(x)` | 返回数字的上入整数，如`ceil(4.1)`返回5 |
  | `trunc(x)` | 返回数字的向0整数，如`ceil(2.3)`返回2 |
  | `gcd(x,y...)` | 返回x,y,...的最大公约数 |
  | `lcm(x,y...)` | 返回x,y,...的最小公倍数 |
  | `cos(x)` | 返回x弧度的余弦值 |
  | `sin(x)` | 返回x弧度的正弦值 |
  | `abs(x)` | 返回数字的绝对值 |
  | `sign(x)` | 返回数学符号，即-1，0，1 |
  | `sqrt(x)` | 返回x的平方根 |
  | `cbrt(x)` | 返回x的立方根 |
  | `exp(x)` | 返回e的x次幂 |
  | `Log(b,x)` | 返回以b为基数的x的对数 |
  | `max(x1, x2, ...)` | 返回参数或序列的最大值 |
  | `min(x1, x2, ...)` | 返回参数或序列的最小值 |

### **随机函数**
  | 随机函数 | 意义（返回值） |
  | - | - |
  | `rand()` | 随机产生0～1的浮点数，可指定行、列数，产生**均匀分布**数 |
  | `randn()` | 随机产生0～1的浮点数，可指定行、列数，产生**正态分布**数 |

### **字符函数**
  | 字符函数 | 意义 |
  | - | - |
  | `Char()` | 将数字转换为字符 |
  | `Int()` | 将字符转换为数字 |

### **字符串函数**
  | 字符串函数 | 意义 |
  | - | - |
  | `SubString(string,start,end)` | 截取字符串中的一部分 |
  | `length(string)` | 获取字符串长度 |
  | `string(a,b)` | 连接字符串a和b |
  | `occursion(str,string)` | 判断字符或字符串str是否在字符串string中，是则返回True，否则返回False |

## 5-2、自定义函数

### **`julia`自定义函数的规则**：
  - 函数代码块以`function`关键词开头，后接函数标识符名称和圆括号`()`；
  - 任何传入参数和自变量必须放在圆括号中；
  - 函数返回值默认最后一个表达式的值，若不想有返回值，则在最后一行加`nothing`；
  - 一旦运行`return`语句，其后的语句不再运行；
  - 函数结束的标志为`end`。
  ```julia
  function 函数名 (参数列表)
      函数体
  end
  ```

### **函数调用**
若如下函数内容写在`julia_test_5_2.jl`中，
```julia
function f(x,y)
    if x > 0
        return (x-y)
    elseif x < 0
        return (x+y)
    else 
        return x*y
    end
end
```
则通过`include("julia_test_5_2.jl")`可调用该函数。

## 5-3、模块
模块是一个包含所有定义的函数和变量的文件。

### **模块定义**
```julia
module my_module1
    export my2
      
    function my1()
        println("Good !!!")
    end
      
    function my2(name)
        println("My name is ", name)
    end
end
```

### **模块调用**
```julia
using my_module1
```

# 6、特征数据类型

## 6-1、数组

### **创建数组**

In [24]:
array1 = [1, 3, 5, 7]

4-element Vector{Int64}:
 1
 3
 5
 7

### **修改数组**

In [25]:
array1[2] = 10

10

使用`push!(array1, 20)`可在数组后添加新数组项：

In [26]:
push!(array1, 20)

5-element Vector{Int64}:
  1
 10
  5
  7
 20

### **删除数组** 

使用`deleteat!(array1, 3)`可删除数组的第三个数字。

In [27]:
deleteat!(array1, 3)

4-element Vector{Int64}:
  1
 10
  7
 20

## 6-2、元组

### **定义元组**

In [28]:
tup1 = (1, 2, 3)  # 当元组仅含一个元素时，需在元素后添加逗号

(1, 2, 3)

In [29]:
tup2 = ()         # 定义空元组

()

## 6-3、字典

### **定义字典**

In [30]:
dict1 = Dict("name"=>"zhang", "age"=>"10")

Dict{String, String} with 2 entries:
  "name" => "zhang"
  "age"  => "10"

### **访问字典的值和键**

In [31]:
println("Name: ", dict1["name"])

Name: zhang


### **修改字典**

In [32]:
dict1["age"] = "20"

"20"

## 6-4、集合

### **定义集合**

In [33]:
a = Set([1, 2, 3])

Set{Int64} with 3 elements:
  2
  3
  1

In [34]:
a = Set()          # 创建空集合

Set{Any}()

# 7、矩阵操作

## 7-1、矩阵的创建与索引

### **创建矩阵**

In [35]:
matrix1 = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [36]:
matrix2 = rand(1:10, 3, 4)  # 创建3×4的随机矩阵

3×4 Matrix{Int64}:
  8  9  7  6
 10  1  9  4
  9  9  2  8

In [37]:
matrix3 = ones(4, 5)        # 创建全1矩阵

4×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [38]:
matrix4 = zeros(5, 6)       # 创建全0矩阵

5×6 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

## 7-2、矩阵的拼接

### **横向拼接**

In [39]:
a = ones(3, 2)
b = zeros(3, 2)

3×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [40]:
c = [a b]

3×4 Matrix{Float64}:
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0

In [41]:
d = hcat([a, b]...)

3×4 Matrix{Float64}:
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0

### **纵向拼接**

In [42]:
a = ones(3, 2)
b = zeros(3, 2)

3×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [43]:
c = [a; b]

6×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [44]:
c = vcat([a, b]...)

6×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

## 7-3、矩阵的运算

### **矩阵加法、矩阵减法**

In [45]:
A = rand(2, 3)

2×3 Matrix{Float64}:
 0.554646  0.151743  0.7479
 0.609116  0.243534  0.320663

In [46]:
B = rand(2, 3)

2×3 Matrix{Float64}:
 0.527592  0.512706  0.458236
 0.955403  0.914521  0.333668

In [47]:
C = A + B

2×3 Matrix{Float64}:
 1.08224  0.66445  1.20614
 1.56452  1.15805  0.654331

In [48]:
D = A - B

2×3 Matrix{Float64}:
  0.0270547  -0.360963   0.289665
 -0.346287   -0.670987  -0.0130053

### **矩阵转置**

In [49]:
A = rand(2, 3)

2×3 Matrix{Float64}:
 0.863094  0.715217  0.819551
 0.512796  0.315086  0.860551

In [50]:
B = A'

3×2 adjoint(::Matrix{Float64}) with eltype Float64:
 0.863094  0.512796
 0.715217  0.315086
 0.819551  0.860551

### **矩阵数乘**

In [51]:
A = rand(2, 3)

2×3 Matrix{Float64}:
 0.991727  0.139925  0.106046
 0.513977  0.528961  0.954604

In [52]:
B = 3 * A

2×3 Matrix{Float64}:
 2.97518  0.419775  0.318138
 1.54193  1.58688   2.86381

### **矩阵乘法**

In [53]:
A = rand(2, 3)

2×3 Matrix{Float64}:
 0.0283034  0.975224  0.733837
 0.930983   0.130539  0.839879

In [54]:
B = rand(3, 4)

3×4 Matrix{Float64}:
 0.885709  0.994643  0.92655   0.806115
 0.579966  0.539115  0.239482  0.740962
 0.866804  0.183304  0.383097  0.0418332

In [55]:
C = A * B

2×4 Matrix{Float64}:
 1.22676  0.688425  0.540904  0.776118
 1.6283   1.15032   1.21562   0.882339

## 7-4、矩阵的函数应用

### **矩阵的基本函数**
- `typeof()`：矩阵的类型。
- `eltype()`：矩阵中元素的类型。
- `length()`：矩阵中元素的个数。
- `ndims()`：矩阵的维度。
- `size()`：矩阵的行数和列数。

### **矩阵的其它创建函数**

In [56]:
a = trues(3, 4)       # 创建3×4的元素全true的矩阵

3×4 BitMatrix:
 1  1  1  1
 1  1  1  1
 1  1  1  1

In [57]:
b = falses(3, 4)      # 创建3×4的元素全false的矩阵

3×4 BitMatrix:
 0  0  0  0
 0  0  0  0
 0  0  0  0

In [58]:
c = reshape(a, 4, 3)  # 重新设置矩阵大小为4×3

4×3 BitMatrix:
 1  1  1
 1  1  1
 1  1  1
 1  1  1

In [59]:
d = copy(b)           # 复制矩阵

3×4 BitMatrix:
 0  0  0  0
 0  0  0  0
 0  0  0  0

### **矩阵的函数运算**

In [60]:
x1 = randn(6, 4)    # 创建一个正态分布矩阵

6×4 Matrix{Float64}:
  0.314813  -0.722766  -1.36335     1.58028
  1.81321    1.0855     0.673011    0.886255
 -1.32169    1.09382    1.55302    -0.899599
 -0.567932  -0.730127  -0.0458421   1.49063
  0.761896  -0.972405   0.341443    1.02841
  1.09036   -1.33051   -0.848158   -1.4082

In [61]:
x2 = round.(x1)     # 对矩阵x1进行四舍五入运算，round与()之间加一个.表示对矩阵进行操作

6×4 Matrix{Float64}:
  0.0  -1.0  -1.0   2.0
  2.0   1.0   1.0   1.0
 -1.0   1.0   2.0  -1.0
 -1.0  -1.0  -0.0   1.0
  1.0  -1.0   0.0   1.0
  1.0  -1.0  -1.0  -1.0

In [62]:
x3 = abs.(x1)       # 对矩阵x1取绝对值

6×4 Matrix{Float64}:
 0.314813  0.722766  1.36335    1.58028
 1.81321   1.0855    0.673011   0.886255
 1.32169   1.09382   1.55302    0.899599
 0.567932  0.730127  0.0458421  1.49063
 0.761896  0.972405  0.341443   1.02841
 1.09036   1.33051   0.848158   1.4082

In [63]:
x4 = sqrt.(x3)      # 对矩阵x3取平方根

6×4 Matrix{Float64}:
 0.561082  0.850156  1.16763   1.25709
 1.34655   1.04187   0.820372  0.941411
 1.14965   1.04586   1.2462    0.948472
 0.753613  0.854475  0.214108  1.22091
 0.872867  0.986106  0.584331  1.01411
 1.0442    1.15348   0.920955  1.18668

In [64]:
x5 = sin.(x1)       # 对矩阵x1进行正弦运算

6×4 Matrix{Float64}:
  0.309639  -0.661461  -0.97856     0.999955
  0.970762   0.884536   0.623343    0.774709
 -0.969133   0.888387   0.999842   -0.783078
 -0.53789   -0.666964  -0.0458261   0.996788
  0.690295  -0.826243   0.334847    0.856481
  0.886795  -0.971269  -0.750064   -0.98681

# 8、文件操作

## 8-1、文件的基本操作

### **文件的创建**
```julia
open(filename, keyword)  # filename为创建的文件名，kerword为创建文件的关键字
```

  `kerword`的参数及意义：
  - `w`：打开文件只用于写入。若文件已存在，则删除原有内容并从头开始编辑。
  - `w+`：打开文件用于读写。若文件已存在，则删除原有内容并从头开始编辑。
  - `a`：打开文件用于追加。若文件已存在，则新内容将会被写入到已有内容之后。
  - `a+`：打开文件用于读写。若文件已存在，则新内容将会被写入到已有内容之后。
  - `r`：打开文件只读。
  - `r+`：打开文件用于读写。

### **写入文件内容**

In [65]:
txt = open("my_file.txt", "w")
write(txt, "hello world!\nhello ustc!!!")
close(txt)

### **读取文件内容**

In [66]:
readlines("my_file.txt")  # 读取打开文件中的所有内容

2-element Vector{String}:
 "hello world!"
 "hello ustc!!!"

In [67]:
readline("my_file.txt")   # 读取打开文件的第一行

"hello world!"

In [68]:
read("my_file.txt", Char)

'h': ASCII/Unicode U+0068 (category Ll: Letter, lowercase)

In [69]:
read("my_file.txt", String)

"hello world!\nhello ustc!!!"

## 8-2、文件中的矩阵操作

### **把矩阵写入文件**

In [70]:
using DelimitedFiles
matrix1 = rand(1:100, 10, 8)
mya = open("my_matrix.txt", "w")
writedlm(mya, matrix1, "\t")
close(mya)

### **从文件中读取矩阵内容**

In [71]:
using DelimitedFiles
myb = open("my_matrix.txt", "r")
readdlm(myb)

10×8 Matrix{Float64}:
 32.0  83.0  92.0   4.0  85.0   95.0  86.0  84.0
 81.0  36.0  68.0  99.0  48.0   42.0   5.0  42.0
 13.0  84.0  75.0  68.0  60.0   93.0  51.0  90.0
 58.0   4.0  85.0  38.0  18.0   43.0  16.0  44.0
 21.0  39.0  89.0  19.0  29.0  100.0  54.0  34.0
 97.0  60.0  60.0  35.0   8.0   68.0   5.0  34.0
 66.0  82.0   7.0  56.0  39.0   10.0  65.0  71.0
 41.0  51.0  52.0  97.0  97.0    2.0   9.0  89.0
 31.0  17.0  10.0  85.0  36.0   17.0  15.0  13.0
 39.0  23.0  85.0  82.0   7.0   40.0  52.0  13.0

# 9、Julia的日期和时间

In [72]:
using Dates

## 9-1、`Date()`函数

### **创建日期的方式**

In [73]:
my_t = Date(2019,4,11)

2019-04-11

### **获取创建日期的年、月、日信息**

In [74]:
t = Date(2019,4,11)

2019-04-11

In [75]:
y = Dates.year(t)

2019

In [76]:
m = Dates.month(t)

4

In [77]:
d = Dates.day(t)

11

In [78]:
ym = Dates.yearmonth(t)

(2019, 4)

In [79]:
md = Dates.monthday(t)

(4, 11)

In [80]:
ymd = Dates.yearmonthday(t)

(2019, 4, 11)

In [81]:
Y = Dates.Year(t)

2019 years

In [82]:
M = Dates.Month(t)

4 months

In [83]:
D = Dates.Day(t)

11 days

### **获取星期几的信息**

In [84]:
t = Date(2019,4,11)

2019-04-11

In [85]:
w = Dates.dayofweek(t)

4

In [86]:
we = Dates.dayname(t)

"Thursday"

### **获取月份的信息**

In [87]:
t = Date(2019,4,11)

2019-04-11

In [88]:
m = Dates.month(t)

4

In [89]:
me = Dates.monthname(t)

"April"

### **获取年份和季节信息**

In [90]:
t = Date(2019,4,11)

2019-04-11

In [91]:
x1 = Dates.dayofyear(t)

101

In [92]:
x2 = Dates.isleapyear(t)

false

In [93]:
x3 = Dates.quarterofyear(t)

2

## 9-2、`DateTime()`函数

### **创建日期时间的方式**

In [94]:
t = DateTime(2019,4,11,12,5,3,2)

2019-04-11T12:05:03.002

### **获取日期时间的信息**

In [95]:
t = DateTime(2019,4,11,12,5,3,2)

2019-04-11T12:05:03.002

In [96]:
y = Dates.year(t)

2019

In [97]:
m = Dates.month(t)

4

In [98]:
d = Dates.day(t)

11

In [99]:
H = Dates.hour(t)

12

In [100]:
M = Dates.minute(t)

5

In [101]:
S = Dates.second(t)

3

In [102]:
MS = Dates.millisecond(t)

2

## 9-3、时间运算

### **`Date()`函数和`DateTime()`函数的运算**

In [103]:
t = DateTime(2019,4,11,12,5,3,2)

2019-04-11T12:05:03.002

In [104]:
t1 = t + Dates.Hour(2)

2019-04-11T14:05:03.002

## 9-4、时间序列

In [105]:
Starttime = Date(2018,1,1)
Endtime   = Date(2018,1,31)
Timestep  = Dates.Day(1)
d = collect(Starttime:Timestep:Endtime)

31-element Vector{Date}:
 2018-01-01
 2018-01-02
 2018-01-03
 2018-01-04
 2018-01-05
 2018-01-06
 2018-01-07
 2018-01-08
 2018-01-09
 2018-01-10
 2018-01-11
 2018-01-12
 2018-01-13
 ⋮
 2018-01-20
 2018-01-21
 2018-01-22
 2018-01-23
 2018-01-24
 2018-01-25
 2018-01-26
 2018-01-27
 2018-01-28
 2018-01-29
 2018-01-30
 2018-01-31